### ISSUE TITLE
Path Problem for Generators

### ISSUE THREAD

**Issue by endriupix** [webreinvent/vaahcli#22]
I have this error when i try to generate new theme with "vaah cms:t" (but I think that it is the same with "vaah cms:m")

![problemVaahCmsCLI](https://github.com/webreinvent/vaahcli/assets/10010807/c689031a-7db8-4499-9cd1-90e56cd7a0bd)

The problem for me is "\" in path in line 35
`let source = '\\skeletons\\vaahcms\\theme\\';`
 
I changed it (from "\" to "/") in these files:

lib/commands/cms/t.js
lib/commands/cms/t-make.js

After these changes I had another problem

![Immagine 2023-05-24 012358](https://github.com/webreinvent/vaahcli/assets/10010807/2a776bf0-bac2-4f19-aa83-f113548dfc01)

The problem for me seems to be the "."  in path after "/usr/lib/node_modules/vaah/lib/libraries"

I remove it from multiple lines in file "lib/libraries/Generator.js" and now all is working

![solved](https://github.com/webreinvent/vaahcli/assets/10010807/9394cd14-678b-41f4-a2c4-463cfdee507e)

**Comment by themodernpk** [comment]
@endriupix thank you for reporting the error. We'll fix it soon

**Comment by themodernpk** [comment]
@endriupix I am unable to replicate the issue, can you please write the OS version? So that we can test. It's working fine on Windows and Mac

**Comment by endriupix** [comment]
Sure, I'm on Windows 11 with Vagrant (2.3.6) on VirtualBox (7.0.8)  provider (i'm using homestead latest version)

This is homestead OS data
vagrant@homestead:~/code/vaahcms$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"

For VaahCms setup i used the official documentation

I think that it works on Windows because it use backslash for paths

**Comment by themodernpk** [comment]
Thank you, will review on Linux based OS

**Comment by endriupix** [comment]
Sorry i forgot PHP version 8.2.1, i don't know if it's relevant

**Comment by themodernpk** [comment]
@endriupix Finally we have released a new version of VaahCLI v3 and this issue is fixed
