### ISSUE TITLE
Directory path for brew different

### ISSUE THREAD

**Issue by bicevskis** [webreinvent/vaahcli#32]
Upon executing the cli command: `npx vaah cms:m`

The following message is generated:

```
✖ Files Generated
  → ENOENT: no such file or directory, scandir '/opt/homebrew/lib/node_modules
…
Error: ENOENT: no such file or directory, scandir '/opt/homebrew/lib/node_modules/vaah/lib/libraries/../../\skeletons\vaahcms\module-vue3\'
```

Possible duplicate of: https://github.com/webreinvent/vaahcli/issues/22

**Comment by themodernpk** [comment]
@bicevskis thank you for raising the issue. We'll look into it.

**Comment by themodernpk** [comment]
@we-vikram-wri231 please test these commands in different OS and environments.

**Comment by bicevskis** [comment]
Hi. Any update on this? :)

**Comment by themodernpk** [comment]
HI @bicevskis, we have found this issue in multiple instances, we're fixing it and will release a major version soon. Thanks for your patience.

**Comment by themodernpk** [comment]
@bicevskis Finally we have released a new version of VaahCLI v3 and this issue is fixed
